### ISSUE TITLE
[EPIC] Launch Phase: DF Test Tech (partial)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#1]
*TODOs*
- [x] Write alpha DF script [Alex]. [Code](https://github.com/oceanprotocol/df-js).
- [x] Write main DF script [Trent]. [Code](https://github.com/oceanprotocol/df-js). [Issue oceanprotocol/df-issues#9](oceanprotocol/df-issues#9)
- [x] In DF script, include data consume volume. (Needs Subgraph work)
- [x] Write blog post draft. [Draft here](https://docs.google.com/document/d/1BVwgZ_reNC25pcYc64Yllcz3tEw43JbwYhS8bQ6IIlg/edit)
