### ISSUE TITLE
SUPER-EPIC: Decentralize & automate DF/VE

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#114]
- [ ] Vesting Wallet contract - Build & test 51%, including exponential. Must reconcile w/ security audits. Ideal: copy & paste battle-tested contracts. [df-issues#41](https://github.com/oceanprotocol/df-issues/issues/41)
- [ ] Router contract - Build & test. It send any incoming funds to target addresses. What: Mapping of [address] : %_to_addr. Multisig governance. Must reconcile w/ security audits. Ideal: copy & paste battle-tested contracts
- [ ] Tech spike: get df-py running on C2D stack [df-py#377](https://github.com/oceanprotocol/df-py/issues/377)
- [ ] (if needed) Tech spikes on web3 logic: K33pr, Gelato [df-issues#107](https://github.com/oceanprotocol/df-issues/issues/107)
- [ ] (if needed) Tech spikes on web3 compute: Ocean c2d, Bacalhau, ocean c2d with bacalhau (best?), Warp, EXM, Cartesi, aleph.im
- [ ] (if needed) Tech spikes on web3 tables: tableland.xyz, [weave_db (with EXM?)](https://twitter.com/exmbuild/status/1589710118764978176?s=51&t=jzOJ6blpKd64ZS88VT0whg), others. [df-issues#116](https://github.com/oceanprotocol/df-issues/issues/116)
- [ ] Tech spike: build POC of final architecture, with a web3 native data pipeline at its core
- [ ] BE: build what's needed to realize backend
- [ ] FE: build what's needed to realize frontend. Ideally, just have to point to different sql etc
- [ ] Get smart contracts audited (or, ideal: copy & paste battle-tested contracts)
- [ ] Deploy to production: vesting wallet, router, df-py rewards, etc.
- [ ] Mint & send remaining 51% from OCEAN contract to vesting wallet [df-priv#9](https://github.com/oceanprotocol/df-private/issues/9)

**Comment by idiom-bytes** [comment]
Issues that are happening right now, will be documented here as they are to be resolved as the outcome of this epic.
- Move data from epoch.json to upstream systems that serve this information (start time, end time, rewards)
- Move data from gdrive, and from having to be saved/stored/copied+pasted, to permaweb (data is stored/retrieved automatically)

**Comment by idiom-bytes** [comment]
Hi, I have updated all references, removed all dependencies, and migrated everything over to [issue#134](https://github.com/oceanprotocol/df-issues/issues/134)

Please take a look at it, perhaps clean up the items in here, and close this epic.

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
