### ISSUE TITLE
df.md step 7 issues: rewards are 0 (and shouldn't be); user should claim both passive + active rewards

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#127]
### Background / motivation

(From an email thread of Trent & Roberto)

T: In ocean.py/READMEs/df.md, section 7 is to claim OCEAN rewards. When I was running it, I found that it said I got 0.0 OCEAN rewards. Do you know what's up?

R: I wonder if it's because step #7 still uses the passive rewards, rather than active rewards?

T: maybe that's part of it. But it should have given passive rewards too.

### TODOs

- [ ] Change step 7 such that user claims both passive + active rewards
- [ ] Ensure that passive rewards are > 0. Fix bugs as needed
- [ ] Ensure that active rewards are >0. Fix bugs as needed

Note: I put this in df-issues, not ocean.py, so that it's easier to track from DF/VE board. (ocean.py isn't on that board, and we don't want it there because it has many non-DF/VE issues)

**Comment by trentmc** [comment]
One possibility: maybe just wait for 2 weeks not one week

**Comment by trentmc** [comment]
Super-old. I haven't heard issues about this recently. Likely obsolete. Closing.
