### ISSUE TITLE
Decentralize DF Main

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#131]
### Problem:
There are parts of the DF stack that do not resolve well to simple onchain checks, balances, and rewards.

To solve for this, Ocean requires a multi-chain solution and decentralized compute stack to handle the execution and decentralization of it's dispense operations. This epic should solve for the compute/reward function calculation and the execution the fund distribution against the vesting/routing contracts.

The output of this epic should execute everything required to dispense both Active & Passive rewards through the vesting/routing contracts.

### DoD:
- [ ] Tech spike: get df-py running on C2D stack [df-py#377](https://github.com/oceanprotocol/df-py/issues/377)
- [ ] (if needed) Tech spikes on web3 logic: K33pr, Gelato [df-issues#107](https://github.com/oceanprotocol/df-issues/issues/107)
- [ ] (if needed) Tech spikes on web3 compute: Ocean c2d, Bacalhau, ocean c2d with bacalhau (best?), Warp, EXM, Cartesi, aleph.im
- [ ] (if needed) Tech spikes on web3 tables: tableland.xyz, [weave_db (with EXM?)](https://twitter.com/exmbuild/status/1589710118764978176?s=51&t=jzOJ6blpKd64ZS88VT0whg), others. [df-issues#116](https://github.com/oceanprotocol/df-issues/issues/116)
- [ ] Tech spike: build POC of final architecture, with a web3 native data pipeline at its core
- [ ] Output of this Epic should integrate and execute the: compute associated with calculating the reward function, outputting all csv files, and organizing the data so rewards can be dispensed.
- [ ] Complete any work required to satisfy: vesting contracts, router contracts, and dispense the rewards as a result of the last step.
- [ ] Most of the rewards work will be done by now. The Passive Rewards / VE dispense can dovetail in here.

**Comment by idiom-bytes** [comment]
This has been restructured inside https://github.com/oceanprotocol/df-private/issues/65

Closing
