### ISSUE TITLE
Funding - GH Actions Compute & Dispense

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#133]
### Problem:

Right now, a lot of work has to e done by hand and via multisigs in order to dispense rewards. We do not want that. We need to move to a decentralized model where everything flows autonomously.

At the end of this epic, we should have both the vesting and routing contracts tested e2e, audited, and deployed so they can be funded and turned on.

This epic should be agnostic to how it will be dispensed, but should provided sufficient abstraction so it can be activated by any system, in a secure manner. Whether through something like Github Actions, or a secure job in a distributed compute blockchain.

The dispensing and execution of it, should be treated and executed in a separate epic.

### DoD:
- [ ] Vesting Wallet contract - Build & test 51%, including exponential. Must reconcile w/ security audits. Ideal: copy & paste battle-tested contracts. [df-issues#41](https://github.com/oceanprotocol/df-issues/issues/41)
- [ ] Router contract - Build & test. It send any incoming funds to target addresses. What: Mapping of [address] : %_to_addr. Multisig governance. Must reconcile w/ security audits. Ideal: copy & paste battle-tested contracts
- [ ] Get smart contracts audited (or, ideal: copy & paste battle-tested contracts)
- [ ] Deploy to production: vesting wallet, router, df-py rewards, etc... whatever is required to execute this stack
- [ ] DEPENDENCY: Before completing this and turning it on, a compute/dispense solution needs to be completed and signed off. It could be GHActions or C2D.
- [ ] Mint & send remaining 51% from OCEAN contract to vesting wallet [df-priv#9](https://github.com/oceanprotocol/df-private/issues/9)

**Comment by idiom-bytes** [comment]
This has been restructured inside https://github.com/oceanprotocol/df-private/issues/65

Closing
