### ISSUE TITLE
C2D E2E - Finalize v0.1

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#134]
### Problem:
There might be some glue, whether cli or visually, required to finalize the magic behind #131 and #133.
In order to finalize this, we might need to look at our stack, and perhaps additional tools (web app) .

By the end of this epic, all required tooling and basic setup is in place to execute the MVP requirements behind the stack for Reward Function + VEDF, end-to-end.

There will likely be additional tooling and systems required to build, let's continue to expand once we complete the major requirements to complete the first major release that gets us closer to a proper end-to-end solution.

### DoD:
- [ ] DF-PY: build what's needed to realize tooling
- [ ] DF-SQL: build what's needed to realize data availability
- [ ] BE: build what's needed to realize backend
- [ ] FE: build what's needed to realize frontend. Ideally, just have to point to different sql etc
- [ ] Close this epic when everything is working together, and the first E2D execution completed.

**Comment by idiom-bytes** [comment]
Documenting issues that are happening right now, and that will be resolved by this epic, here:

[df-web #404](https://app.zenhub.com/workspaces/ve--df-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/404)
- This should be resolved by vesting and router contracts.
- Move data from epoch.json to upstream systems that serve this information (start time, end time, rewards)

[df-issues #112](https://app.zenhub.com/workspaces/ve--df-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/122) 
- This should be resolved by decentralized data pipelines
- Temporary solution would be to automate gh-actions to dump df-py output to arweave
- Any time we have to generate, store, or deal with df-py. It's all local, manual, and opposite of what we want. We would prefer this be always available via a query/api, or in permaweb such as arweave so it can be accessed at any time.

**Comment by trentmc** [comment]
When we decentralize DF, C2D is only one candidate way to do it. Closing this issue, instead use the higher-level epic to prioritize tech spikes to explore possibilities.

**Comment by trentmc** [comment]
Also note:

> There might be some glue, whether cli or visually, required to finalize the magic behind #131 and #133.

Both of these issues have been completed.
