### ISSUE TITLE
Funding - GH Actions Compute & Dispense

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#136]
### Problem:
Before we go through the process of decentralizing the code base, we can get a lot of wins by automating the pipeline and killing our overhead.

Vesting & Router contracts should be deployed by this point, and we should be able to configure our GH Action environment, to safely talk to these contracts to automate our dispense.

When this Epic completes, Github Actions will be able to dispense the funding of the vesting + routing contract. This could be indirect via a call to a multisig, or some other verifiable manner. Or the vesting/dispense contract is safe enough, that the executor (Github Actions) could be changed in case of an attack.

### DoD:
- [ ] VEDF weekly rewards are being made available via the vesting contract
- [ ] VEDF weekly reward distributions (i.e. what % goes to passive, active, etc...) are being done via the routing contracts
- [ ] VEDF weekly reward calculations and funding dispensing is executed by GH Actions 
- [ ] VEDF weekly reward dispense is executed via a request to a multisig SAFE
- [ ] At the end of this epic, everything is automated via Github Actions + Vesting + Routing Contracts + any other required component

**Comment by idiom-bytes** [comment]
closing in light of https://github.com/oceanprotocol/df-private/issues/65
