### ISSUE TITLE
Write "DF Onboarding guide" blog post & tweetstorm draft

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#15]
**Motivation**

Whereas oceanprotocol/df-issues#14 is for the main "announcement" blog post, we also want a blog post that gives a detailed walk-through with screenshots to make it easy as possible for people to try out. That's the aim of this post.

**TODOs:**
- [x] In GDocs, write initial blog post draft
- [ ] For blog post, get feedback from OPF core team (incl Alex, Trent, Razvan, Matthias) & key community members (Kai? Other?), incorporate changes
- [ ] For blog post, ensure all images sorted out. Maybe get help from marcom
- [ ] Copy blog post into medium, ready to get published. Ensure in Ocean Protocol publication. 
- [ ] In GDocs, write tweetstorm draft of 3-10 tweets. Include images / links as needed
- [ ] For tweetstorm, get feedback from OPF core team (incl Alex, Trent, Razvan), incorporate changes
- [ ] (on announcement day) Have Marcom publish blog post, and tweetstorm
