### ISSUE TITLE
Update blog post numbers, finalize

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#40]
**TODOs**

- [x] Ensure that Gsheet has ratcheting 10 - 25 - 50 - 100%
- [x] Ensure Gsheet has appropriate input values. Review output values / rewards numbers
- [x] Ensure that blog post includes ratcheting
- [x] Update rewards numbers in post
- [x] Update plots in post 
- [x] Do a final review / edit of draft

What will follow this issue: get it signed off, including B+R for numbers [df-issues#43](https://github.com/oceanprotocol/df-issues/issues/43)

**Key Links**

- [Blog post Gdoc](https://docs.google.com/document/d/1BVwgZ_reNC25pcYc64Yllcz3tEw43JbwYhS8bQ6IIlg/edit#)
- [DF Gsheet](https://docs.google.com/spreadsheets/d/1_1SUpImOxVY8lVEinExzTVHQRjKev7519sWkzMiCCB4/edit#gid=958420163)
