### ISSUE TITLE
Extend vw-cli for DF 51% OCEAN supply

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#41]
**TODOs**

- [x] https://github.com/oceanprotocol/vw-cli/issues/7
- [x] https://github.com/oceanprotocol/vw-cli/issues/9
- [x] https://github.com/oceanprotocol/vw-cli/issues/8
- [x] https://github.com/oceanprotocol/vw-cli/issues/11
- [x] Deploy exp'l wallet to Ropsten, test it
- [x] Deploy to Eth mainnet, test with small token amounts, be ready to send 51% to it

**Comment by trentmc** [comment]
Done
