### ISSUE TITLE
Claim & smart-stake. FE & BE

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#67]
### What

Have a button to be able to claim & re-LP, where the claimed rewards will allocate the rewards into 3-5 pools with predicted best gains, found via optimization.

### On implementing

Predicted best gains are wrt to reward function RF = log(stake + offset) + log(vol + offset).

- First cut idea: run once per week
- Problem: too many LPs pile into “top” pools, which makes the pools less attractive 
- Solution: re-run the optimization periodically, eg every 10 min, or every time someone LPs, or as requested by the user in dfweb app. Let's assume the latter.

The computation will likely run an optimization algorithm. We can explore ways to make it run super-fast. This means it'll be in python. Expect that it'll run in dftool; though if we can make it lightweight enough, maybe it can be in pyscript in the browser.

### TODOs

- [ ] [Trent] Add to df-py: a method that computes the top 3-5 pools, and outputs a csv  
- [ ] [Trent] Try to optimize its speed further
- [ ] Decide on a name for the button
- [ ] Build the rest. Interaction among dftool, dfweb, and DFRewards.sol. Look to learnings from building "Claim & Stake" button ([link](https://github.com/oceanprotocol/df-issues/issues/68)).

### Notes
This is in df-issues since it involves both FE and BE.

### Appendix: What to label the button? 

Ideas:
- "Claim & smart-stake"
- "LP Wizard". Ht Malte for "wizard" term:)
- "Claim & wizard-stake"
- "Claim & optimize-stake"
- "Staking wizard (with claim)"

Discussion: 
- needs to be simple & approachable for user, yet accurate
- "claim & smart-stake" seems to be the best fit so far. More ideas welcome:)
