### ISSUE TITLE
Dashboard PoC - pyscript + dftools + SimplePool + TVL - Boilerplate App

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-issues#77]
### Goal

(_This_ issue holds tech spikes towards [this higher-level issue](https://github.com/oceanprotocol/df-issues/issues/78).)

Get a basic boilerplate w/ pyscript that enables us to start serving data
- Pyscript app w/ a TVL dashboard
- Migrate dftool query + simplepool + all network query to app
- Create a dashboard will report TVL per network + across all network
- Use https://pyscript.net/examples/ UI to enable us to explore and build different dashboards w/ this vanilla implementation

### Overview
[Pyscript Farmboards]
Decided to "do something simple" and just report TVL in a a new folder inside the pyscript repo.
Decided this would be easier and accurate if I was able to port basic dfpy/query.py functionality over.

I approached this from a few different angles:
- reading pyscript examples => hello world implementation
- dftools query functionality to get all pools + tvl, across all chains subsequent useful functionality (SimplePool)
- other dftool functionality that is dependent in order to get this basic implementation in place

Am still going through the df-py/dftools query code in order to unravel how it's setup. The main dependencies that I'm working through about at the moment (which I'm trying to write code to circumvent), deals with dfpy being "tightly coupled" with Brownie. This takes place in a few locations:
- In SimplePool in particular is where I'm looking into.
- Other places, like networkutils, I am simply returning the raw address per chain rather than the brownie object.
- Other functionality dependant on this _filterOutPurgatory and oceanutil.calcDID
- When it comes to queries to the subgraph, SimplePool and basic data fetching/handling, could perhaps be more detached from Brownie.

This is still heavy WIP. The python/graphql part still does not work.
I invited the nile engineers to it.
https://github.com/idiom-bytes/pyscript-farmboarding

**[This GDoc](https://docs.google.com/document/d/1HMsYnC8Bw4ag7otCFTHIhnZ2vkIvVoO6sgguEpI28lE/edit#) analyzes options.**

Live dashboard: https://test-dashboards.oceandao.org/examples/

### TODO:
- [ ] Develop a PoC pyscript app that leverages dftools + query + chains + SimplePools, that enables us to aggregate & summarize various v4 metrics that are readily available
- [ ] Output TVL per network + across all network
- [ ] Use https://pyscript.net/examples/ outline to break it down into separate dashboards

**Comment by idiom-bytes** [comment]
I think we should keep it open and use it as an outline for dashboard requirements. Perhaps the epic. I.E. Point to the design/requirements doc, and maintain other more minute deliverables to get v0.1 completed.

**Comment by trentmc** [comment]
OK. Then at least let's rename away from "dune"

**Comment by idiom-bytes** [comment]
Continued to clean dfpy functionality (i.e. writing different GQL requests that removed dependencies) and cleaned up a bunch of code. For the sake of simplicity/speed, I decided to just setup a very basic request/query in order to KISS and validate that things are working.

Ended up learning that pyscript does not support requests because everything is done asynchronously.
Instead, you need to use asyncio and pyodide.http => pyfetch in order to do it all async.

This lead to more rabbit holes and debugging in order for me to get something that works.
The unfortunate part is that I can't just run the same code off a local .py file.

I have created a few more test .html files in order to debug this functionality, and get a simple request against the subgraph to yield good data. This took me to the end of my day.

**Comment by idiom-bytes** [comment]
Update
- Reshuffled folders & files around to make DX easier to navigate
- Renamed example single-page.html to be more descriptive
- `root/examples/subgraph_orders.html` is now up and running. You can now see first 1000 orders from v4.polygon.

**Comment by idiom-bytes** [comment]
Update
- `root/examples/dfsql_poolinf.html` is now up and running, and serves data from dfsql prod db

**Comment by idiom-bytes** [comment]
Hi @trentmc, I'm going to roll the TVL dashboard into a separate issue so I can close this one.

I think we got the initial PoC + hooking up a bunch of data sources in place.
- Pyscript PoC
- Querying from subgraph pools/transactions/consumes across all chains
- Querying from the DB

I'd like to close this one to complete the work laid out above.

For us to calc TVL + graph this there is some work left.
I propose we capture that remaining work in a separate ticket.

**Comment by trentmc** [comment]
If you want to close this issue, go for it; please do create a new issue, and copy + paste the key specs into the new issue.

**Comment by idiom-bytes** [comment]
New issue [can be found here](https://github.com/oceanprotocol/df-issues/issues/92), which references the TVL/DCV dashboard defined above.

Closing this ticket as it delivered the initial PoC (minus target TVL/DCV dashboard)
