### ISSUE TITLE
Write main DF script

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-issues#9]
**Scope:** 
- Do "calculate rewards"
- Do "dispense funds"
- Not for this issue: data consume volume, other features. Other github issues handle that.
- In py, so Trent can drive more readily. And, more amenable to data science analysis. 

**Links:**
- **[df-py repo](https://github.com/oceanprotocol/df-py)**. Related: [df-js repo](https://github.com/oceanprotocol/df-js/) (alpha).

**TODOs:**
- [x] Go through tutorials on [GraphQL](https://graphql.org)  & [TheGraph](https://thegraph.com) with python. 
  - GraphQL: [GraphQL queries](https://graphql.org/learn/queries/), [GraphQL spec](http://spec.graphql.org/October2021/)
  - TheGraph: [docs](https://thegraph.com/docs/en/), [all subgraphs](https://thegraph.com/explorer/)
  - Ocean * TheGraph: [ocean-subgraph](https://github.com/oceanprotocol/ocean-subgraph), [graph-node (fork)](https://github.com/oceanprotocol/graph-node)
  - py * TheGraph:
    - [Google search](https://www.google.com/search?q=%22thegraph%22+%22python%22&sxsrf=APq-WBvBhUPZaFjVjgy_hD1hpsoKwOOWRg%3A1647061406799&ei=niksYverMIOUxc8Pr5GnuAk&ved=0ahUKEwj38szw5b_2AhUDSvEDHa_ICZcQ4dUDCA4&uact=5&oq=%22thegraph%22+%22python%22) 
    - **["Use The Graph to query Ethereum data in Python"](https://cryptomarketpool.com/use-the-graph-to-query-ethereum-data-in-python/)**
    - [TheGraph-Intro ipynb](https://github.com/danielzak/thegraph-intro/blob/main/0.1-Intro.ipynb) 
    - [Bubbletea](https://forum.thegraph.com/t/a-framework-to-build-any-data-applications-entirely-on-the-decentralized-web3-infrastructures/1979/12)
- [x] In df-py: tests: create a local test setup of oceanv4 contracts 
  - [x] Initiate df-py from VestingWallet-CLI repo [`923e97`](https://github.com/oceanprotocol/df-py/commit/923e9729a65601e8ca47aab1af46ecdb1f1c223f)
  - [x] In df-py repo, copy in oceanprotocol/contracts [v4 branch](https://github.com/oceanprotocol/contracts/tree/v4main_postaudit)
  - [x] In tokenspice, clean up all oceanv4 stuff. [GH issue](https://github.com/tokenspice/tokenspice/issues/154)
  - [x] In df-py repo: Write basic test to set up fake assets + pools. Leverage tokenspice. [`d41447`](https://github.com/oceanprotocol/df-py/commit/d41447e059024553ec877e7d9e212620bb8d40a6)
  - [x] In df-py repo: have fake consume [`c10483`](https://github.com/oceanprotocol/df-py/commit/c104832e2b2ddc1a46b68175d4ea021498e04573)
- [x] In df-py: create CLI stubs for "compute rewards", "dispense funds", more
- [x] Get local subgraph going. Resources: (a) docs from TheGraph (b) Ocean Barge 
- [x] In df-py: implement "compute rewards"
  - [x] Implement in tests
  - [x] Implement in CLI 
- [x] In df-py: implement "dispense funds".
  - [x] Implement in tests
  - [x] Implement in CLI [`52e0c4`](https://github.com/oceanprotocol/df-py/commit/52e0c4b5f5c41ee314ef2bc70f15972623c9b17b)
